plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.mehdi.sunwidget'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mehdi.sunwidget'
        minSdk 23
        targetSdk 35
        versionCode (project.findProperty('versionCode') ?: '1').toString().toInteger()
        versionName (project.findProperty('versionName') ?: '1.0').toString()
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}
